apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: astros
  name: astros
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: astros
    spec:
      containers:
      - image: astros
        name: astros
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
