apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: flask
  name: flask
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      run: flask
  template:
    metadata:
      labels:
        run: flask
    spec:
      containers:
      - image: krudisar/flask:v2
        imagePullPolicy: Always
        name: flask
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
