
apiVersion: v1
kind: Service
metadata:
  labels:
    run: flask
  name: flask
  namespace: default
spec:
  ports:
  - nodePort: 31111 # define or leave it blank (should be 30000-32767)
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask
  sessionAffinity: None
  type: NodePort
#status:
#  loadBalancer:
#    ingress:
#    - hostname: localhost