---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb
        version: v1
    spec:
      containers:
        - image: mongo
          name: mongodb
          ports:
            - containerPort: 27017
